server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:CE0980uk@cluster0-xidgh.gcp.mongodb.net/aion
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master

keycloak:
  admin:
    realm: master
    username: admin
    password: admin