server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:CE0980uk@cluster0-xidgh.gcp.mongodb.net/aion
  main:
    allow-bean-definition-overriding: true

okta:
  oauth2:
    issuer: https://dev-107152.okta.com/oauth2/default
    client-id: 0oa1hqx3paKP6vfAU357
    client-secret: pMrOivyrICs9Z5eYHTl32XE2RdRhngzndav5Fyt2
    scopes: openid
  client:
    token: 00bD4gBD69X6THNeGdsO1SYt2B5lydDtJ7PEj19gZ2
    org-url: https://dev-107152.okta.com

storage:
  protocol: gs
  bucket: aion-project.appspot.com
  thumbnail:
    width: 256
    height: 256