server:
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:CE0980uk@cluster0-xidgh.gcp.mongodb.net/aion
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/master

# Apparently, Writing data to Google Cloud Storage blobs doesn't work. XD
#
# Replace the storage configs with following configs once it works.
# protocol: gs
# bucket: aion-storage
#
# Until local file system will be used as storage (LOL!)
storage:
  protocol: file
  bucket: home/udesh/aion-storage
  thumbnail:
    width: 256
    height: 256

keycloak:
  admin:
    realm: master
    username: admin
    password: admin